/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staff_view;

import controller.AccountInforMap;
import controller.Administrator;
import controller.BackupDataUtils;
import controller.ExitOptionBackup;
import controller.RestoreDataUtils;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Form;
import model.GeneralSecretary;
import model.MapStaffAndStudent;
import view.LoginForm;

/**
 *
 * @author kuriy
 */
public class MessSecretaryHomePage extends javax.swing.JFrame {

    static DefaultTableModel model = new DefaultTableModel();
    static GeneralSecretary secretary;
    
    public MessSecretaryHomePage(int hallNumber) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.addListener();
        ExitOptionBackup.exitOption(this);
        
        //
        secretary = Administrator.getListGeneralSecretarys().get(hallNumber - 1);
        secretary.setListFormMess(RestoreDataUtils.restoreFormListData(new File("mess" + hallNumber + ".txt")));
        addDataToTable();
        
        //backup
        ExitOptionBackup.exitOptionList(this, hallNumber, secretary.getListFormMess());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messFrame = new javax.swing.JFrame();
        popupMenu = new javax.swing.JPopupMenu();
        forwardToMess = new javax.swing.JMenuItem();
        declineMenuItem = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messTable = new javax.swing.JTable();

        javax.swing.GroupLayout messFrameLayout = new javax.swing.GroupLayout(messFrame.getContentPane());
        messFrame.getContentPane().setLayout(messFrameLayout);
        messFrameLayout.setHorizontalGroup(
            messFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        messFrameLayout.setVerticalGroup(
            messFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        forwardToMess.setText("Forward To Mess");
        forwardToMess.setToolTipText("");
        forwardToMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardToMessActionPerformed(evt);
            }
        });
        popupMenu.add(forwardToMess);

        declineMenuItem.setText("Decline");
        declineMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineMenuItemActionPerformed(evt);
            }
        });
        popupMenu.add(declineMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mess Form");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        messTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room", "Name", "Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(messTable);
        if (messTable.getColumnModel().getColumnCount() > 0) {
            messTable.getColumnModel().getColumn(0).setResizable(false);
            messTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            messTable.getColumnModel().getColumn(1).setResizable(false);
            messTable.getColumnModel().getColumn(1).setPreferredWidth(1);
            messTable.getColumnModel().getColumn(2).setResizable(false);
            messTable.getColumnModel().getColumn(2).setPreferredWidth(1);
            messTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void addRowMessTable(Object[] object) {
        MessSecretaryHomePage.model = (DefaultTableModel) messTable.getModel();
        model.addRow(object);
    }
    
    public static void addDataToTable(){
        for(Form form : secretary.getListFormMess()){
            String name = AccountInforMap.getName(form.getStudentID());
            String room = AccountInforMap.getRoom(form.getStudentID());
            Object[] object = new Object[]{form.getStudentID(), name, room, form.getSummary()};
            addRowMessTable(object);
        }
    }


    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
        List<Form> listForm = Administrator.getListMessAssistant().get(secretary.getHallNumber()-1).getListForm();
        
        // backup
        File file = new File("wardene" + secretary.getHallNumber()+".txt");
        BackupDataUtils.backupListForm(listForm, file);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void forwardToMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardToMessActionPerformed
        int row = messTable.getSelectedRow();
        
        try {           
            Form form = secretary.getListFormMess().get(row);
            secretary.forwardFormMess(form);
            secretary.reviseFormMess(form);
            
            JOptionPane.showMessageDialog(rootPane, "Forward Successfully!");
        } catch (ArrayIndexOutOfBoundsException e) {
            /*...*/
        } finally {
            ((DefaultTableModel) messTable.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_forwardToMessActionPerformed

    private void declineMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineMenuItemActionPerformed
        int row = messTable.getSelectedRow();
        secretary.reviseFormMess(secretary.getListFormMess().get(row));
        ((DefaultTableModel) messTable.getModel()).removeRow(row);
    }//GEN-LAST:event_declineMenuItemActionPerformed

    private void addListener() {
        //
        messTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    doubleClickOnTable(messTable, messTable);
                }
            }
        });

        //
        messTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    popupMenu.show(messTable, e.getX(), e.getY());
                }
            }
        });
    }

    private void doubleClickOnTable(Component evt, JTable a) {
        int row = a.getSelectedRow();
        StringBuilder sBuilder = new StringBuilder();

        try {
            String id = String.valueOf(a.getValueAt(row, 0));
            String name = String.valueOf(a.getValueAt(row, 1));
            String room = String.valueOf(a.getValueAt(row, 2));
            String des = String.valueOf(a.getValueAt(row, 3));
            sBuilder.append("ID: ").append(id).append(", ").append("Name: ").append(name).
                    append(", Room: ").append(room).append("\n").append("Description: ").append(des);
        } catch (ArrayIndexOutOfBoundsException e) {

        } finally {
            JOptionPane.showMessageDialog(evt, sBuilder);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessSecretaryHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessSecretaryHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessSecretaryHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessSecretaryHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MessSecretaryHomePage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem declineMenuItem;
    private javax.swing.JMenuItem forwardToMess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private static javax.swing.JFrame messFrame;
    private static javax.swing.JTable messTable;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
