/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staff_view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Hall;

/**
 *
 * @author kuriy
 */
public class RoomStatus extends javax.swing.JFrame {

    /**
     * Creates new form RoomStatus
     */
    public RoomStatus() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void createObject() {

        for (int i = 0; i < 6; i++) {
            int statusA = 0;
            int statusB = 0;
            int statusC = 0;
            //create room name;
            
//            int idx = i + 1;
            
            String a = "A" + i;
            String b = "B" + i;
            String c = "C" + i;

            if (!(RoomInfor.getSingleRoom().get(a) == 0)) {
                statusA = RoomInfor.getSingleRoom().get(a);
            }

            if (!(RoomInfor.getTwoRoom().get(b) == 0)) {
                statusB = RoomInfor.getTwoRoom().get(b);
            }

            if (!(RoomInfor.getFourRoom().get(c) == 0)) {
                statusC = RoomInfor.getFourRoom().get(c);
            }
            Object[] object = new Object[]{statusA, statusB, statusC};
            addRowTable(object);
        }
    }

    public static void addRowTable(Object[] object) {
        DefaultTableModel model = (DefaultTableModel) RoomStatus.roomStatusTable.getModel();
        model.addRow(object);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        chooseRoomMenuItem = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomStatusTable = new javax.swing.JTable();

        chooseRoomMenuItem.setText("Choose Room");
        chooseRoomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRoomMenuItemActionPerformed(evt);
            }
        });
        popupMenu.add(chooseRoomMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roomStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room for one", "Room for two", "Room for four"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        roomStatusTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(roomStatusTable);
        if (roomStatusTable.getColumnModel().getColumnCount() > 0) {
            roomStatusTable.getColumnModel().getColumn(0).setResizable(false);
            roomStatusTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseRoomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRoomMenuItemActionPerformed
        int collumn = roomStatusTable.getSelectedColumn();
        int row = roomStatusTable.getSelectedRow();   
        if (collumn == 0) {
            if (RoomInfor.getSingleRoom().get("A" + row) == 1) {
                showError();
            } else {
                CreateStudentAccount.roomTextField.setText("A" + row);              
            }
        }

        if (collumn == 1) {
            if (RoomInfor.getTwoRoom().get("B" + row) == 2) {
                showError();
            } else {
                CreateStudentAccount.roomTextField.setText("B" + row);             
            }
        }

        if (collumn == 2) {
            if (RoomInfor.getFourRoom().get("C" + row) == 4) {
                showError();
            } else {
                CreateStudentAccount.roomTextField.setText("C" + row);             
            }
        }

        this.dispose();
    }//GEN-LAST:event_chooseRoomMenuItemActionPerformed

    public void showError() {
        JOptionPane.showMessageDialog(this, "Room is full",
                "Error", JOptionPane.ERROR_MESSAGE);
    }

    public static void addToRoomStatus(HashMap<String, Integer> roomType, String roomName, int numOfStudent) {
        int tempStudent = roomType.get(roomName) + numOfStudent;
        roomType.put(roomName, tempStudent);
    }

    static void addListener() {
        //
        roomStatusTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    popupMenu.show(roomStatusTable, e.getX(), e.getY());
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem chooseRoomMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JPopupMenu popupMenu;
    public static javax.swing.JTable roomStatusTable;
    // End of variables declaration//GEN-END:variables
}
